In [2]:
import numpy as np 
import torch 
import torch.nn as nn
import torch.nn.functional as F

In [5]:
a = torch.tensor([[0,1.3], [-0.6,0], [0, 0.9], [-0.8, 0]])
a, a.shape 

(tensor([[ 0.0000,  1.3000],
         [-0.6000,  0.0000],
         [ 0.0000,  0.9000],
         [-0.8000,  0.0000]]),
 torch.Size([4, 2]))

In [6]:
b = torch.tensor([[0,0,-0.8,0,-0.6], [0.5,0,0,0.8,0]])
b, b.shape 

(tensor([[ 0.0000,  0.0000, -0.8000,  0.0000, -0.6000],
         [ 0.5000,  0.0000,  0.0000,  0.8000,  0.0000]]),
 torch.Size([2, 5]))

In [7]:
torch.mm(a,b)

tensor([[0.6500, 0.0000, 0.0000, 1.0400, 0.0000],
        [0.0000, 0.0000, 0.4800, 0.0000, 0.3600],
        [0.4500, 0.0000, 0.0000, 0.7200, 0.0000],
        [0.0000, 0.0000, 0.6400, 0.0000, 0.4800]])